apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyJavaApp
  labels:
    app: MyJavaApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyJavaApp
  template:
    metadata:
      labels:
        app: MyJavaApp
    spec:
      containers:
      - name: java1
        image: darshanvv26/java:latest
        ports:
        - containerPort: 8080
